version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/frontend/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
