# Generated by Django 3.0.8 on 2020-07-01 16:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeUnite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nom', models.CharField(max_length=255, unique=True, verbose_name="Nature de l'unité (masse, volume ...)")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nom', models.CharField(max_length=255, unique=True, verbose_name="Nom de l'unité")),
                ('abbreviation', models.CharField(max_length=255, unique=True, verbose_name='Abbréviation')),
                ('rapport', models.DecimalField(decimal_places=20, max_digits=20)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unites.TypeUnite')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
