# Generated by Django 3.0.8 on 2020-07-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unite',
            name='rapport',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
