# Generated by Django 3.0.8 on 2020-09-15 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unites', '0002_auto_20200711_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeunite',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='unite',
            old_name='nom',
            new_name='name',
        ),
    ]
