# Generated by Django 3.0.8 on 2020-07-01 16:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientFrigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_peremption', models.DateField(verbose_name='Date de péremption')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogues.Ingredient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
