# Generated by Django 3.0.8 on 2020-07-27 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unites', '0002_auto_20200711_0912'),
        ('frigo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientfrigo',
            name='unite',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to='unites.Unite'),
            preserve_default=False,
        ),
    ]
