name: Python CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: pipenv install --dev
        working-directory: ./backend
      - name: Run flake8
        run: pipenv run flake8 --config=setup.cfg --max-complexity 10
        working-directory: ./backend
      - name: Run unit tests
        run: pipenv run pytest
        working-directory: ./backend/maprochainerecette
