name: Python CI

on:
  push:
    branches: [master, backend]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: |
          pipenv install --dev
        working-directory: ${{ env.working-directory }}
      - name: Test with pytest
        run: |
          pipenv run pytest
        working-directory: ${{ env.working-directory }}
